### ISSUE TITLE
Does not work with Conda environments

### ISSUE THREAD

**Issue by stared** [ryszard/think#2]
Using [fish shell](https://fishshell.com/) and [starship](https://starship.rs/) on macOS.
A command that runs in (an activated) Python [Conda](https://docs.conda.io/en/latest/) environment does not work in `think`.

```shell
❯ think
think> Install a package with poetry
Install a package using Poetry package manager.
poetry add <package_name>

run> poetry add genson
fish: Unknown command: poetry
fish: 
poetry add genson
^~~~~^
think> exit

my_folder on  main is 📦 v0.1.0 via 🐍 v3.10.11 via 🅒 some_conda_env took 47s 
❯ poetry add gensom  # works
```

**Comment by ryszard** [comment]
Might be an issue related to how PATH is being set, and from a quick Google search it seems like fish is doing something special about variables. Can you do something like `echo $PATH` in fish (sans conda), with conda, and through think?

**Comment by ryszard** [comment]
Also, can you please see if the problem persists without starship?
